# fill at runtime by wizard
# interface=        # set by wizard (e.g. wlan0)
# ssid=             # set by wizard (e.g. dronectl-<short>)
# channel=          # set by wizard (e.g. 6)
# preamble=1
# hw_mode=g
# wme_enabled=1
# ieee80211n=1
# auth_algs=1
# ignore_broadcast_ssid=0
# wpa=2
# wpa_passphrase=   # set by wizard (e.g. dronectl-setup)
# wpa_key_mgmt=WPA-PSK
# wpa_pairwise=CCMP
# rsn_pairwise=CCMP